# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0024_auto_20151217_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='country_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
