# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0029_remove_prediction_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.Prediction')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.RaceResult')),
            ],
        ),
    ]
