# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0030_racescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racescore',
            name='prediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.Prediction'),
        ),
        migrations.AlterField(
            model_name='racescore',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.RaceResult'),
        ),
    ]
